@url = http://localhost:3000/api
@json = Content-Type: application/json
###
get {{url}}
{{json}}

###查询用户接口
get {{url}}/users

### 注册
post {{url}}/register
{{json}}

{
  "username":"user312",
  "password":"123456",
  "email":"1360967095@qq.com",
  "sex":"wwwew",
  "register_time":"2020-01-12",
  "phone":"13480333124" 
}

### 登录
post {{url}}/login
{{json}}

{
  "username":"user32",
  "password":"123456"
}
###
post {{url}}/articleDetails
{{json}}

{
  "id":"5e8403e85dc78f23a086180b"
}
###个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNjY1N2RkOGY1YzJkMTRiOGMyYjU0NSIsImlhdCI6MTU4Mzc2Njc2NX0.1I9maXvWTuXMMVJ2tp_yez-qXmYh_kFR0LVw9gdYWFY

###添加文章
post {{url}}/addArticle
{{json}}

{
    "title": "方晓龙测试1",
    "content": "018年末，回首今年，感觉整个圈子的气氛是惨不忍睹的。昔日的大佬，昔日的老板大土豪，在这个寒冬渐渐的败落。有些人在死撑自己的信誉，苦死也撑着，这些人是我所以尊重、仰慕、崇拜的。然而也些人不是，借着这个寒冬，他们打破了底线，当起了老赖（这里没有双引号，是真正的老赖）。
              2018",
    "image": "show3.jpg",
    "time": "2020-3-22 10:10:59",
    "author":" 作者",
    "views":" 1222",
    "comment_count":"231",
    "sort_id": "qqqwq",
    "label_id":"qweqw2"
}

###查询文章列表
get {{url}}/articles
{{json}}

###更新文章
put {{url}}/updateArticle
{{json}}

{
  {
    "article_id":"2",
      "title": "测试2014草根寻梦本模板来自杨青个博客的(2014草根寻梦",
      "content": "本模板动，同样也是基于帝国CMS开源程序搭建的本模板来自杨青个博客的(2014草根寻梦本模板来自杨青个本模板来自杨青个博客的(2014草根寻梦本模板来自杨青个",
      "image": "show2.jpg",
      "time": "2020-02-05",
      "author":" 作者2222223",
      "views":" 1232",
      "comment_count":"2323231",
      "sort_id": "2321",
      "label_id":"2322"
  }
}
###添加分类
post {{url}}/addSort
{{json}}

{
"name":"123111",
"description":"123123"
}

###查看分类
get {{ url }}/sort
{{ json }}

###添加标签
post {{url}}/addLabel
{{json}}

{
"name":"日志1",
"description":"时刻分享"
}

###查看标签
get {{ url }}/label
{{ json }}

###查看留言

get {{ url }}/leaveMessage
{{json}}

###添加留言
post {{ url }}/addLM
{{ json}}

{
  "createTime":"2020-04-01 12:02:23",
  "content":"测试111",
  "name":"方晓龙111111",
  "Iurl":"1"
}